<html>
  <head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	  <title><?php echo $this->title; ?></title>
	  <link rel="stylesheet" href="/resources/css/reset.css" type="text/css" media="screen" />
	  <link rel="stylesheet" href="/resources/css/style.css" type="text/css" media="screen" />
	  <link rel="stylesheet" href="/resources/css/invalid.css" type="text/css" media="screen" />
	  <link rel="stylesheet" href="/css/jquery.alerts.css" type="text/css" media="screen" />
	  <link rel="stylesheet" type="text/css" href="/jQuery_plugin/confirm/jquery.confirm/jquery.confirm.css" />
	   	
	  <script type="text/javascript" src="/resources/scripts/jquery-1.3.2.min.js"></script>
	  <script type="text/javascript" src="/jQuery_plugin/confirm/jquery.confirm/jquery.confirm.js"></script>
	  <script type="text/javascript" src="/resources/scripts/simpla.jquery.configuration.js"></script>
	  <script type="text/javascript" src="/resources/scripts/facebox.js"></script>
	  <script type="text/javascript" src="/resources/scripts/jquery.wysiwyg.js"></script>
	  <script type="text/javascript" src="/js/jquery.alerts.js"></script>
	</head>
	<body>
	  <div id="body-wrapper">
		<div id="sidebar">
		  <div id="sidebar-wrapper">
			<?php echo $this->partial('/layout/menu.phtml', array('menu'=>$menu))?>
        </div>
      </div>
      <div id="main-content">
        <h2>欢迎 <font color=red><?php echo $userInfo['username']; ?></font>登陆系统</h2>
		<p id="page-intro">你想做什么?</p>
        <div id="content"><?php echo $this->content;?></div>
        <div id="footer">
		  <small>
			&#169; Copyright 2012 Shanghai Inlay | Powered by <a href="">Shanghai Inlay SWG</a> | <a href="#">Top</a>
		  </small>
		</div>
      </div>
    </div>
    <?php echo $this->inlineScript() ?>
  </body>
</html>