<html>
  <head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>网站后台登陆页</title>
	<link rel="stylesheet" href="/resources/css/reset.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="/resources/css/style.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="/resources/css/invalid.css" type="text/css" media="screen" />
	<script type="text/javascript" src="/resources/scripts/jquery-1.3.2.min.js"></script>
  </head>
  <body id="login">
   	<?php echo $this->content; ?>        
    <?php echo $this->inlineScript() ?>
  </body>
</html>